// <auto-generated />
namespace PizzaExpress.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201704231926364_1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
