// <auto-generated />
namespace PizzaExpress.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class AtualizarBanco1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtualizarBanco1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151912314_AtualizarBanco1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
